"""added a password_lock column in the users table

Revision ID: 20284303d914
Revises: bc7322b6861d
Create Date: 2018-02-04 13:56:17.163285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20284303d914'
down_revision = 'bc7322b6861d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_lock', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_lock')
    # ### end Alembic commands ###
