"""added an  author column from the pitches table

Revision ID: 34328b45843e
Revises: ab2d1f399855
Create Date: 2018-02-09 15:13:45.297889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34328b45843e'
down_revision = 'ab2d1f399855'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('author', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'author')
    # ### end Alembic commands ###
