"""added a new column in the pitches table

Revision ID: 4ad70c94cfd0
Revises: fd161f515adf
Create Date: 2018-02-07 15:37:17.528695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ad70c94cfd0'
down_revision = 'fd161f515adf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('comments', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'comments')
    # ### end Alembic commands ###
