"""modified the users table

Revision ID: 79dd4197037d
Revises: e8f9c6eb7c06
Create Date: 2018-02-05 15:12:05.823880

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '79dd4197037d'
down_revision = 'e8f9c6eb7c06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('author', sa.String(), nullable=True))
    op.add_column('pitches', sa.Column('body', sa.String(), nullable=True))
    op.add_column('pitches', sa.Column('downvotes', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('posted', sa.DateTime(), nullable=True))
    op.add_column('pitches', sa.Column('upvotes', sa.Integer(), nullable=True))
    op.drop_constraint('pitches_user_id_fkey', 'pitches', type_='foreignkey')
    op.drop_column('pitches', 'pitch_content')
    op.drop_column('pitches', 'downvote')
    op.drop_column('pitches', 'user_id')
    op.drop_column('pitches', 'upvote')
    op.drop_column('pitches', 'published_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('published_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('upvote', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('downvote', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('pitch_content', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('pitches_user_id_fkey', 'pitches', 'users', ['user_id'], ['id'])
    op.drop_column('pitches', 'upvotes')
    op.drop_column('pitches', 'posted')
    op.drop_column('pitches', 'downvotes')
    op.drop_column('pitches', 'body')
    op.drop_column('pitches', 'author')
    # ### end Alembic commands ###
