"""deleted the categories table and added two new columns in the pitches table

Revision ID: 7a61debc4d77
Revises: ecd32cd88ea4
Create Date: 2018-02-05 12:43:38.703725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a61debc4d77'
down_revision = 'ecd32cd88ea4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('title', sa.String(length=255), nullable=True))
    op.drop_column('pitches', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'title')
    # ### end Alembic commands ###
