"""added a categories column in the pitches table

Revision ID: 87872fdab47a
Revises: 7a61debc4d77
Create Date: 2018-02-05 12:46:04.712980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87872fdab47a'
down_revision = '7a61debc4d77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('category', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'category')
    # ### end Alembic commands ###
