"""modified the users table

Revision ID: b45d81571c32
Revises: 79dd4197037d
Create Date: 2018-02-05 15:14:04.458437

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b45d81571c32'
down_revision = '79dd4197037d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('downvote', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('pitch_content', sa.String(), nullable=True))
    op.add_column('pitches', sa.Column('published_at', sa.DateTime(), nullable=True))
    op.add_column('pitches', sa.Column('upvote', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pitches', 'users', ['user_id'], ['id'])
    op.drop_column('pitches', 'posted')
    op.drop_column('pitches', 'upvotes')
    op.drop_column('pitches', 'author')
    op.drop_column('pitches', 'body')
    op.drop_column('pitches', 'downvotes')
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'bio')
    op.add_column('pitches', sa.Column('downvotes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('upvotes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('posted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.drop_column('pitches', 'user_id')
    op.drop_column('pitches', 'upvote')
    op.drop_column('pitches', 'published_at')
    op.drop_column('pitches', 'pitch_content')
    op.drop_column('pitches', 'downvote')
    # ### end Alembic commands ###
